"""A real multi-wavelength inverse fit: reproducing Hennessy et al.'s SO2 bias.

Why this is a different, larger thing than examples/hennessy_reproduction.py
------------------------------------------------------------------------------
That script compared a raw, single-wavelength forward-model ΔR against
Hennessy et al.'s finding and found -- honestly, not by construction --
that the two quantities don't behave the same way, because their result
lives in a *fitted* SO2 recovered from a multi-wavelength spectral
inversion that separates melanin from hemoglobin, not in a raw ΔR. This
script builds that inversion for real: a one-layer forward model is
fit, by nonlinear least squares across several wavelengths, to a
spectrum generated by this project's own two-layer Monte Carlo engine,
and the *fitted* SO2 is compared against the *true* SO2 the two-layer
model was given -- the same comparison Hennessy et al. make.

The speed problem, and how it's handled without leaving the validated
engine
------------------------------------------------------------------------
A nonlinear fit needs the forward model evaluated many times (tens to
low hundreds of iterations for a 3-parameter least-squares problem).
Running fresh Monte Carlo for every one of those evaluations would take
minutes to hours. Diffusion theory would be fast, but it is not this
project's own validated engine, and would quietly swap the physics the
paper is about for a different approximation inside the one component
that matters most.

The approach here keeps the Monte Carlo engine as the sole source of
the mu_a -> Rd relationship, and makes the optimizer fast a different
way: at each of the fitted wavelengths, Rd(mu_a) is *precomputed* on a
grid via the real engine (with the bulk scattering held fixed, matching
the one-layer model's own fixed scattering), and a monotone interpolant
is built from that grid. The optimizer then calls the interpolant, not
fresh Monte Carlo, on each iteration -- every number the interpolant
returns still traces back to an actual simulated Rd, just precomputed
rather than recomputed. The interpolant's own accuracy is checked
against held-out Monte Carlo points before it is trusted (see
`_validate_lookup_tables`), the same "don't trust a shortcut without
checking it" rule this project has applied everywhere else.

What "true" spectra are generated from
----------------------------------------
The two-layer "ground truth" spectrum at each SO2 is generated by the
*actual*, uninterpolated `simulate_layered_medium` at every fitted
wavelength -- full Monte Carlo, not the lookup table (the lookup table
is only used inside the one-layer fit's forward model).

Author: Noureddin Sedki
License: MIT
"""

import sys
from pathlib import Path

import numpy as np
from scipy.interpolate import PchipInterpolator
from scipy.optimize import least_squares

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from photon_transport_toolkit import SlabOpticalProperties, simulate_slab  # noqa: E402
from photon_transport_toolkit.layered_media import Layer, LayeredMedium, simulate_layered_medium  # noqa: E402
from photon_transport_toolkit.tissue_optics import (  # noqa: E402
    blood_absorption_mm,
    epidermis_layer,
    melanin_absorption_mm,
    reduced_scattering_power_law,
)

WAVELENGTHS_NM = [520.0, 560.0, 600.0, 660.0, 700.0]  # within the verified 500-740nm Hb table
N_INDEX = 1.4

EPIDERMIS_THICKNESS = 0.08   # mm, mid-range of Hennessy's tested Z0
DERMIS_THICKNESS = 1.5       # mm
TRUE_MELANIN_FRACTION = 0.04
TRUE_C_HB = 2.3              # g/L, tissue concentration -- see blood_absorption_mm docstring

# One-layer fit model's fixed scattering (not itself a fit parameter, so
# the 3-unknown problem -- melanin fraction, C_Hb, SO2 -- stays
# well-posed with 5 wavelengths): the same thickness-weighted bulk
# average used everywhere else in this project.
FIT_MUSP_REF_MM = 3.5   # at 550 nm, a blend of the epidermis/dermis values used elsewhere
FIT_B = 1.3
FIT_G = 0.85

N_TRUTH_PHOTONS, N_TRUTH_BATCHES = 15_000, 6
N_LUT_PHOTONS, N_LUT_BATCHES = 4_000, 4
# Widened after checking the actual bulk-averaged mu_a this configuration produces
# (0.05-0.47 mm^-1 across the fitted wavelengths and both true SO2 values) --
# the original 0.0005-0.13 grid silently clipped every evaluation to its own
# upper edge, which is exactly why the first attempt at this fit failed
# (fitted parameters landed on the initial guess, huge residual -- caught by
# checking the fit quality rather than trusting a returned number).
MU_A_GRID = np.array([0.005, 0.01, 0.02, 0.035, 0.05, 0.07, 0.09, 0.12,
                      0.16, 0.20, 0.26, 0.33, 0.42, 0.55, 0.70])


def _onelayer_slab(mu_a: float, wavelength_nm: float) -> SlabOpticalProperties:
    musp = reduced_scattering_power_law(wavelength_nm, FIT_MUSP_REF_MM, FIT_B)
    mus = musp / (1 - FIT_G)
    return SlabOpticalProperties(mu_a=mu_a, mu_s=mus, g=FIT_G,
                                 thickness=EPIDERMIS_THICKNESS + DERMIS_THICKNESS,
                                 n_medium=N_INDEX, n_outside=1.0)


def build_lookup_tables(seed: int = 0):
    """Rd(mu_a) via real Monte Carlo, on a grid, at each fitted wavelength."""
    tables = {}
    for wl in WAVELENGTHS_NM:
        rd_vals = []
        for mu_a in MU_A_GRID:
            slab = _onelayer_slab(mu_a, wl)
            res = simulate_slab(slab, n_photons=N_LUT_PHOTONS, n_batches=N_LUT_BATCHES, seed=seed)
            rd_vals.append(res.diffuse_reflectance)
        tables[wl] = PchipInterpolator(MU_A_GRID, np.array(rd_vals), extrapolate=True)
    return tables


def _validate_lookup_tables(tables, n_checks: int = 3, seed: int = 999):
    """Held-out spot checks: interpolant vs. fresh Monte Carlo, at mu_a
    values NOT on the grid. Must agree before the fit is trusted."""
    rng = np.random.default_rng(seed)
    print("Lookup-table validation (held-out points, interpolant vs. fresh MC):")
    worst_rel_err = 0.0
    for wl in WAVELENGTHS_NM:
        mu_a_test = float(rng.uniform(MU_A_GRID[1], MU_A_GRID[-2]))
        slab = _onelayer_slab(mu_a_test, wl)
        res = simulate_slab(slab, n_photons=8000, n_batches=6, seed=seed)
        predicted = float(tables[wl](mu_a_test))
        rel_err = abs(predicted - res.diffuse_reflectance) / max(res.diffuse_reflectance, 1e-6)
        worst_rel_err = max(worst_rel_err, rel_err)
        z = abs(predicted - res.diffuse_reflectance) / res.diffuse_reflectance_stderr
        print(f"  {wl:.0f} nm, mu_a={mu_a_test:.4f}: interp={predicted:.4f}  "
              f"MC={res.diffuse_reflectance:.4f}+/-{res.diffuse_reflectance_stderr:.4f}  "
              f"({z:.1f} sigma, {rel_err*100:.2f}% rel. error)")
    print(f"  worst-case relative error: {worst_rel_err*100:.2f}%\n")
    return worst_rel_err


def onelayer_spectrum(params, tables):
    """(f_mel, c_hb, so2) -> predicted Rd at every fitted wavelength, via the LUTs."""
    f_mel, c_hb, so2 = params
    out = np.zeros(len(WAVELENGTHS_NM))
    for i, wl in enumerate(WAVELENGTHS_NM):
        mu_a = f_mel * melanin_absorption_mm(wl) + blood_absorption_mm(wl, so2, c_hb_g_per_l=c_hb)
        mu_a = float(np.clip(mu_a, MU_A_GRID[0], MU_A_GRID[-1]))
        out[i] = tables[wl](mu_a)
    return out


def twolayer_truth_spectrum(so2_true: float, seed: int = 1):
    """The actual two-layer Rd(wavelength) -- full Monte Carlo, every wavelength."""
    out = np.zeros(len(WAVELENGTHS_NM))
    stderr = np.zeros(len(WAVELENGTHS_NM))
    for i, wl in enumerate(WAVELENGTHS_NM):
        epidermis = epidermis_layer(wl, thickness_mm=EPIDERMIS_THICKNESS,
                                    melanin_fraction=TRUE_MELANIN_FRACTION)
        dermis_mua = blood_absorption_mm(wl, so2_true, c_hb_g_per_l=TRUE_C_HB)
        dermis = Layer(mu_a=dermis_mua, mu_s=20.0, g=0.90, thickness=DERMIS_THICKNESS, n=N_INDEX)
        medium = LayeredMedium(layers=[epidermis, dermis], n_outside_top=1.0, n_outside_bottom=1.0)
        res = simulate_layered_medium(medium, n_photons=N_TRUTH_PHOTONS, n_batches=N_TRUTH_BATCHES, seed=seed)
        out[i] = res.diffuse_reflectance
        stderr[i] = res.diffuse_reflectance_stderr
    return out, stderr


def fit_onelayer(target_spectrum, tables):
    """Nonlinear least squares: recover (f_mel, c_hb, so2) from a target spectrum."""
    def residuals(params):
        return onelayer_spectrum(params, tables) - target_spectrum

    x0 = np.array([0.003, 2.0, 0.5])
    bounds = ([0.0003, 0.1, 0.0], [0.02, 8.0, 1.0])
    result = least_squares(residuals, x0, bounds=bounds, xtol=1e-13, ftol=1e-13,
                           x_scale=[0.003, 2.0, 0.5], max_nfev=2000)
    return result.x, result


def main():
    print("=" * 96)
    print("SPECTRAL INVERSE FIT -- a real reproduction attempt of Hennessy et al.'s SO2 bias")
    print("=" * 96)
    print(f"Wavelengths: {WAVELENGTHS_NM} nm  |  true melanin fraction={TRUE_MELANIN_FRACTION}, "
          f"true C_Hb={TRUE_C_HB} g/L\n")

    print("Building Rd(mu_a) lookup tables via Monte Carlo "
          f"({len(WAVELENGTHS_NM)} wavelengths x {len(MU_A_GRID)} grid points)...")
    tables = build_lookup_tables()
    worst_err = _validate_lookup_tables(tables)
    if worst_err > 0.05:
        print("STOP: lookup-table error exceeds 5% -- refine the grid before trusting the fit.")
        return

    print("Generating two-layer 'truth' spectra via full Monte Carlo (every wavelength)...")
    results = {}
    for so2_true in (0.30, 0.70):
        target, target_se = twolayer_truth_spectrum(so2_true)
        fitted_params, fit_result = fit_onelayer(target, tables)
        f_mel_fit, c_hb_fit, so2_fit = fitted_params
        results[so2_true] = (so2_fit, f_mel_fit, c_hb_fit, fit_result.cost)
        print(f"\nTrue SO2 = {so2_true:.0%}:")
        print(f"  target spectrum Rd = {np.round(target, 4)}")
        print(f"  fitted: f_mel={f_mel_fit:.4f}  C_Hb={c_hb_fit:.3f} g/L  SO2_fit={so2_fit:.1%}")
        print(f"  fit residual cost = {fit_result.cost:.2e}  "
              f"(mean |residual| = {np.mean(np.abs(fit_result.fun)):.5f})")

    so2_fit_30, _, _, _ = results[0.30]
    so2_fit_70, _, _, _ = results[0.70]
    bias_30 = so2_fit_30 - 0.30
    bias_70 = so2_fit_70 - 0.70

    print("\n" + "=" * 96)
    print("RESULT")
    print("=" * 96)
    print(f"True SO2 = 30%  ->  fitted SO2 = {so2_fit_30:.1%}   bias = {bias_30:+.1%}")
    print(f"True SO2 = 70%  ->  fitted SO2 = {so2_fit_70:.1%}   bias = {bias_70:+.1%}")
    flipped = (bias_30 < 0) != (bias_70 < 0)
    print(f"\nSign of fitted-SO2 bias flips between 30% and 70% true SO2: {'YES' if flipped else 'no'}")


if __name__ == "__main__":
    main()
